name: tkgl-fps
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.13=hb9d3cd8_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.2=h3394656_1
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - contourpy=1.3.1=py311hd18a35c_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.0=h59595ed_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - expat=2.6.4=h5888daf_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.3=py311h2dc5d0c_1
  - freetype=2.12.1=h267a509_2
  - future=1.0.0=pyhd8ed1ab_1
  - graphite2=1.3.13=h59595ed_1003
  - h5py=3.13.0=nompi_py311hb639ac4_100
  - harfbuzz=10.2.0=h4bba637_0
  - hdf5=1.14.3=nompi_h2d575fe_109
  - hyperopt=0.2.7=pyhd8ed1ab_1
  - icu=75.1=he02047a_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py311hd18a35c_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.3=h59595ed_0
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libclang-cpp19.1=19.1.7=default_hb5137d0_0
  - libclang13=19.1.7=default_h9c6a7e4_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.12.1=h332b0f4_0
  - libdeflate=1.23=h4ddbbb0_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.2=h2ff4ddf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - libllvm19=19.1.7=ha7bfdaf_0
  - liblzma=5.6.3=hb9d3cd8_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.45=h943b412_0
  - libpq=17.2=h3b95a9b_1
  - libsqlite=3.47.2=hee588c1_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=hd9ff511_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.13.5=h8d12d68_1
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib=3.10.0=py311h38be061_0
  - matplotlib-base=3.10.0=py311h2b939e6_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.0.1=h266115a_4
  - mysql-libs=9.0.1=he0572af_4
  - ncurses=6.5=h2d0b736_2
  - openldap=2.6.9=he970967_0
  - openpyxl=3.1.5=py311h50c5138_1
  - openssl=3.5.0=h7b32b05_1
  - pcre2=10.44=hba22ea6_2
  - pip=24.2=py311h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - py4j=0.10.9.8=pyhd8ed1ab_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pyside6=6.8.1=py311h9053184_0
  - python=3.11.8=hab00c5b_0_cpython
  - python_abi=3.11=5_cp311
  - qhull=2020.2=h434a139_5
  - qt6-main=6.8.1=h588cce1_2
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py311h06a4308_0
  - sqlite=3.47.2=h9eae976_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py311h9ecbd09_0
  - unicodedata2=16.0.0=py311h9ecbd09_0
  - wayland=1.23.1=h3e06ad9_0
  - wheel=0.44.0=py311h06a4308_0
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - aimsim-core==2.2.2
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - astartes==1.3.0
      - attrs==24.3.0
      - chemprop==2.0.5
      - configargparse==1.7
      - descriptastorus==2.8.0
      - dill==0.3.9
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.4.2
      - lightning==2.5.0.post0
      - lightning-utilities==0.11.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mhfp==1.9.6
      - mordredcommunity==2.0.6
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.17
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==24.2
      - padelpy==0.1.16
      - pandas==2.2.3
      - pandas-flavor==0.6.0
      - pillow==11.0.0
      - propcache==0.2.1
      - psutil==6.1.1
      - pygments==2.18.0
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - rdkit==2024.3.6
      - rich==13.9.4
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - six==1.17.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - torch==2.5.1
      - torchmetrics==1.6.0
      - tqdm==4.67.1
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - xarray==2024.11.0
      - yarl==1.18.3
