name: tkgl
channels:
  - conda-forge
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - tmap
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - argon2-cffi-bindings=21.2.0=py39h5eee18b_1
  - async-lru=2.0.4=py39h06a4308_0
  - beautifulsoup4=4.12.3=py39h06a4308_0
  - bleach=6.2.0=py39h06a4308_0
  - brokenaxes=0.4.2=pyhd8ed1ab_0
  - brotli-python=1.0.9=py39h6a678d5_9
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2025.7.14=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cudatoolkit=11.2.2=hbe64b41_10
  - cudnn=8.1.0.77=h90431f1_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - expat=2.4.8=h27087fc_0
  - fontconfig=2.14.0=h8e229c2_0
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h0b5b191_1005
  - h11=0.14.0=py39h06a4308_0
  - icu=68.2=h9c3ff4c_0
  - idna=3.7=py39h06a4308_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - ipykernel=6.29.5=py39h06a4308_0
  - jsonschema=4.23.0=py39h06a4308_0
  - jupyter_client=8.6.0=py39h06a4308_0
  - jupyter_core=5.7.2=py39h06a4308_0
  - jupyter_events=0.10.0=py39h06a4308_0
  - jupyter_server=2.14.1=py39h06a4308_0
  - jupyter_server_terminals=0.4.4=py39h06a4308_1
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=h58526e2_2
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.68.4=h3e27bee_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=he4da1e4_16
  - libuuid=2.32.1=h7f98852_1000
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.12=h72842e0_0
  - matplotlib-base=3.5.2=py39h700656a_0
  - mplcursors=0.6=pyhd8ed1ab_1
  - nbformat=5.10.4=py39h06a4308_0
  - ncurses=6.3=h27087fc_1
  - notebook=7.2.2=py39h06a4308_1
  - ogdf=1.2.0=h2bc3f7f_0
  - openbabel=3.1.1=py39hee2736e_2
  - openssl=1.1.1w=h7f8727e_0
  - pcre=8.45=h9c3ff4c_0
  - pip=22.2.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - prometheus_client=0.21.0=py39h06a4308_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.13=haa1d7c7_2
  - python-fastjsonschema=2.20.0=py39h06a4308_0
  - python-json-logger=3.2.1=py39h06a4308_0
  - python_abi=3.9=2_cp39
  - readline=8.1.2=h7f8727e_1
  - rfc3339-validator=0.1.4=py39h06a4308_0
  - rfc3986-validator=0.1.1=py39h06a4308_0
  - rpds-py=0.22.3=py39h4aa5aa6_0
  - setuptools=63.4.1=py39hf3d152e_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.5=py39h06a4308_0
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tmap=1.0.6=py39h2bc3f7f_0
  - tomli=2.0.1=py39h06a4308_0
  - traitlets=5.14.3=py39h06a4308_0
  - typing_extensions=4.12.2=py39h06a4308_0
  - websocket-client=1.8.0=py39h06a4308_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.12=h5eee18b_3
  - pip:
      - absl-py==2.1.0
      - affine==2.4.0
      - aiobotocore==2.12.3
      - aiohttp==3.9.5
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - alabaster==0.7.16
      - albumentations==1.4.4
      - anndata==0.10.7
      - annotated-types==0.6.0
      - anyio==3.7.1
      - anyqt==0.2.0
      - argon2-cffi==23.1.0
      - array-api-compat==1.6
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==23.2.0
      - autocommand==2.2.2
      - autograd==1.6.2
      - autograd-gamma==0.5.0
      - ax-platform==0.3.7
      - babel==2.14.0
      - backports-tarfile==1.1.1
      - baycomp==1.0.3
      - biopython==1.78
      - biothings-client==0.3.1
      - botocore==1.34.69
      - botorch==0.10.0
      - bottleneck==1.3.8
      - cachetools==5.3.3
      - cattrs==23.2.3
      - cellxgene-census==1.10.2
      - cffi==1.16.0
      - chardet==5.2.0
      - cheroot==10.0.1
      - cherrypy==18.10.0
      - choreographer==1.0.9
      - cirpy==1.0.2
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==3.0.0
      - colour==0.1.5
      - comm==0.2.2
      - commonmark==0.9.1
      - contourpy==1.2.1
      - cryptography==42.0.5
      - cycler==0.12.1
      - dataclasses==0.6
      - debugpy==1.8.1
      - decorator==5.1.1
      - deep-forest==0.1.7
      - deeppurpose==0.1.5
      - descriptastorus==2.6.1
      - dgllife==0.3.2
      - dictdiffer==0.9.0
      - docutils==0.21.2
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - faerun==0.4.7
      - fastjsonschema==2.21.1
      - filelock==3.13.4
      - fiona==1.9.6
      - flatbuffers==24.3.25
      - fonttools==4.51.0
      - formulaic==1.0.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - future==1.0.0
      - fuzzywuzzy==0.18.0
      - gast==0.4.0
      - geopandas==0.14.3
      - get-annotations==0.1.2
      - gget==0.28.4
      - google-auth==2.29.0
      - google-auth-oauthlib==1.2.2
      - google-pasta==0.2.0
      - gpytorch==1.11
      - grpcio==1.62.2
      - h5py==3.11.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.20.3
      - hyperopt==0.2.7
      - imagecodecs==2024.1.1
      - imageio==2.34.1
      - imagesize==1.4.1
      - imbalanced-learn==0.12.2
      - imblearn==0.0
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - interface-meta==1.3.0
      - ipython==8.18.1
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jaraco-classes==3.4.0
      - jaraco-collections==5.1.0
      - jaraco-context==5.3.0
      - jaraco-functools==4.0.1
      - jaraco-text==4.0.0
      - jaxtyping==0.2.28
      - jedi==0.19.1
      - jeepney==0.8.0
      - jinja2==3.1.3
      - jmespath==1.0.1
      - joblib==1.4.0
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.1
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.10
      - kaleido==0.1.0
      - keras==2.15.0
      - keras-preprocessing==1.1.2
      - keyring==25.1.0
      - keyrings-alt==5.0.1
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - libclang==18.1.1
      - lifelines==0.28.0
      - lightgbm==4.3.0
      - lightning-utilities==0.11.2
      - linear-operator==0.5.1
      - llvmlite==0.42.0
      - logistro==1.1.0
      - lxml==5.2.1
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - mhfp==1.9.6
      - mistune==3.1.0
      - ml-dtypes==0.3.2
      - mock==5.1.0
      - mordred==1.2.0
      - more-itertools==10.2.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - multipledispatch==1.0.0
      - mygene==3.2.2
      - mypy-extensions==1.0.0
      - mysql-connector-python==8.0.29
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nest-asyncio==1.6.0
      - networkx==2.8.8
      - notebook-shim==0.2.4
      - numba==0.59.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.9.0.80
      - openpyxl==3.0.10
      - opentsne==1.0.1
      - opt-einsum==3.3.0
      - orange-canvas-core==0.1.35
      - orange-widget-base==4.22.0
      - orjson==3.11.0
      - overrides==7.7.0
      - packaging==24.0
      - pandas==2.1.4
      - pandas-flavor==0.6.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - patsy==0.5.6
      - pbr==6.0.0
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.0
      - plotly==5.21.0
      - portend==3.2.0
      - prettytable==3.10.0
      - progressbar2==4.4.2
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.43
      - protobuf==4.25.7
      - psutil==5.9.8
      - pubchempy==1.0.4
      - pure-eval==0.2.2
      - py4j==0.10.9.7
      - pyarrow==16.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycocotools==2.0.7
      - pycparser==2.22
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pygments==2.17.2
      - pynndescent==0.5.12
      - pyparsing==3.1.2
      - pyproj==3.6.1
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyqtgraph==0.13.6
      - pyqtwebengine==5.15.6
      - pyqtwebengine-qt5==5.15.2
      - pyre-extensions==0.0.30
      - pyro-api==0.1.2
      - pyro-ppl==1.9.0
      - pysmiles==1.0.1
      - pytdc==0.4.17
      - python-dateutil==2.9.0.post0
      - python-louvain==0.16
      - python-utils==3.8.2
      - pytorch-lightning==2.2.3
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.2
      - qasync==0.27.1
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - rasterio==1.3.10
      - rdkit==2023.9.5
      - recommonmark==0.7.1
      - referencing==0.36.1
      - requests==2.31.0
      - requests-cache==1.2.0
      - requests-oauthlib==2.0.0
      - rfc3986==1.5.0
      - rsa==4.9
      - rtree==1.2.0
      - s3fs==2024.3.1
      - scanpy==1.9.6
      - scikit-image==0.22.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.12.2
      - secretstorage==3.3.3
      - send2trash==1.8.3
      - serverfiles==0.3.1
      - session-info==1.0.0
      - shapely==2.0.4
      - signaturizer==1.1.16
      - simplejson==3.20.1
      - slidingwindow==0.0.14
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - snuggs==1.4.7
      - somacore==1.0.8
      - spektral==1.2.0
      - sphinx==7.3.7
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - stack-data==0.6.3
      - statsmodels==0.14.2
      - stdlib-list==0.10.0
      - subword-nmt==0.3.8
      - sympy==1.12
      - tempora==5.8.0
      - tenacity==8.2.3
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.15.1
      - tensorflow-addons==0.22.0
      - tensorflow-estimator==2.15.0
      - tensorflow-gpu==2.10.0
      - tensorflow-hub==0.16.1
      - tensorflow-io-gcs-filesystem==0.36.0
      - termcolor==2.4.0
      - terminado==0.18.1
      - tf-keras==2.15.1
      - threadpoolctl==3.4.0
      - tifffile==2024.4.18
      - tiledb==0.25.1
      - tiledbsoma==1.7.3
      - tinycss2==1.4.0
      - torch==2.2.2
      - torchmetrics==1.3.2
      - torchvision==0.17.2
      - tornado==6.4
      - tqdm==4.65.0
      - triton==2.2.0
      - typeguard==2.13.3
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.11.0
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - ujson==5.10.0
      - umap-learn==0.5.6
      - uri-template==1.3.0
      - url-normalize==1.4.3
      - urllib3==1.26.18
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - werkzeug==3.0.2
      - wget==3.2
      - widgetsnbextension==4.0.10
      - wrapt==1.14.1
      - xarray==2024.3.0
      - xgboost==2.0.3
      - xlrd==2.0.1
      - xlsxwriter==3.2.0
      - xmltodict==0.13.0
      - yapf==0.40.2
      - yarl==1.9.4
      - zc-lockfile==3.0.post1
      - zipp==3.18.1